import sys

def solve():
    import math
    input = sys.stdin.buffer.read
    data = input().split()
    N = int(data[0])
    a = list(map(int, data[1:N+1]))
    
    for ai in a:
        if ai < 3:
            print("NO")
            continue
        total_slots = ai
        # The first and last slots are occupied, so available slots are total_slots - 2
        available_slots = total_slots - 2
        # We need exactly one empty slot that divides total_slots
        # So, we need exactly one divisor of total_slots in the range [1, available_slots]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots - 2]
        # So, we need to check if there is exactly one divisor of total_slots in [1, total_slots - 2]
        # The divisor must be in the range [1, total_slots -