import sys

def solve():
    import sys
    input = sys.stdin.buffer.read
    data = input().split()
    T = int(data[0])
    results = []
    for i in range(1, T + 1):
        N = int(data[i])
        if N == 1:
            results.append('1')
        else:
            # The sequence is generated by alternating between 6^k - 1 and 6^k + 5
            # For N odd: 6^k - 1
            # For N even: 6^k + 5
            k = (N + 1) // 2
            if N % 2 == 1:
                res = 6**k - 1
            else:
                res = 6**k + 5
            results.append(str(res))
    print('\n'.join(results))

if __name__ == '__main__':
    solve()