import sys
import collections

def solve():
    input = sys.stdin.buffer.read().split()
    T = int(input[0])
    idx = 1
    for _ in range(T):
        w = input[idx]
        K = int(input[idx+1])
        idx += 2
        
        count = collections.Counter(w)
        freq = list(count.values())
        freq.sort()
        
        # Try to make the frequencies as close as possible
        # We can try all possible frequencies that are within K of each other
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the range [min_freq, max_freq]
        # We can try all possible frequencies that are in the