import sys

def solve():
    import sys
    input = sys.stdin.buffer.read
    data = input().split()
    
    idx = 0
    T = int(data[idx])
    idx += 1
    
    results = []
    
    for _ in range(T):
        n = int(data[idx])
        sx = int(data[idx+1])
        sy = int(data[idx+2])
        ex = int(data[idx+3])
        ey = int(data[idx+4])
        bx = int(data[idx+5])
        by = int(data[idx+6])
        idx += 7
        
        # Calculate Manhattan distance between start and end
        moves = abs(sx - ex) + abs(sy - ey)
        
        # Check if the bomb is on the direct path
        # If the bomb is on the direct path, we need to detour
        # Check if the bomb is between start and end
        # For Manhattan path, the bomb is on the path if:
        # (bx is between sx and ex) and (by is between sy and ey)
        # or (by is between sy and ey) and (bx is between sx and ex)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is between sy and ey)
        # or (bx is between sx and ex) and (by is