import sys

def solve():
    import sys
    input = sys.stdin.buffer.read
    data = input().split()
    
    idx = 0
    t = int(data[idx])
    idx += 1
    results = []
    
    for _ in range(t):
        n = int(data[idx])
        idx += 1
        p = list(map(int, data[idx:idx + n]))
        idx += n
        
        # For each number i (1-based), find its position in the permutation
        pos = [0] * (n + 1)  # pos[i] is the position of i in the permutation
        for i in range(n):
            pos[p[i]] = i + 1
        
        # Check if the permutation can be generated by the algorithm
        # We simulate the process for each number i from 1 to n
        # At each step, we need to find the positions that are still available
        # and select the one with the maximum count of r_j
        # We use a priority queue to track the positions with maximum count
        # We also need to track the current available positions
        
        available = set(range(1, n + 1))
        for i in range(1, n + 1):
            # Compute r_j for each j from 1 to n
            r = [0] * (n + 1)
            for j in range(1, n + 1):
                if j not in available:
                    continue
                # Find the minimum r_j >= j that is still available
                for k in range(j, n + 1):
                    if k in available:
                        r[j] = k
                        break
            # Compute count_t for each t
            count = [0] * (n + 1)
            for j in range(1, n + 1):
                if r[j] != 0 and r[j] in available:
                    count[r[j]] += 1
            # Find the positions with maximum count
            max_count = -1
            candidates = []
            for t in range(1, n + 1):
                if count[t] > max_count:
                    max_count = count[t]
                    candidates = [t]
                elif count[t] == max_count:
                    candidates.append(t)
            # Now, among the candidates, we need to select the one that is the position of i
            # Because the generator can choose any of the positions with max count
            # So we need to check if pos[i] is among the candidates
            if pos[i] not in candidates:
                results.append("No")
                break
            # Remove the chosen position from available
            available.remove(pos[i])
        else:
            results.append("Yes")
    
    print("\n".join(results))

if __name__ == '__main__':
    solve()