import sys

def solve():
    import sys
    input = sys.stdin.buffer.read
    data = input().split()
    
    idx = 0
    t = int(data[idx])
    idx += 1
    results = []
    
    for _ in range(t):
        n = int(data[idx])
        idx += 1
        p = list(map(int, data[idx:idx + n]))
        idx += n
        
        # For each number i (1-based), find its position in the permutation
        pos = [0] * (n + 1)  # pos[i] is the position of number i in the permutation
        for i in range(n):
            pos[p[i]] = i + 1
        
        # Check if the permutation can be generated by the algorithm
        # We simulate the process for each number from 1 to n
        # At each step i, we need to find the position for i according to the rules
        # We track which positions are still available
        available = set(range(1, n + 1))
        valid = True
        
        for i in range(1, n + 1):
            # Compute r_j for all j from 1 to n
            r = [0] * (n + 1)
            for j in range(1, n + 1):
                # Find the minimum r_j such that r_j >= j and r_j is available
                for k in range(j, n + 1):
                    if k in available:
                        r[j] = k
                        break
                else:
                    r[j] = -1  # not defined
            
            # Compute count_t for all t from 1 to n
            count = [0] * (n + 1)
            for j in range(1, n + 1):
                if r[j] != -1 and r[j] in available:
                    count[r[j]] += 1
            
            # Find the positions with maximum count
            max_count = -1
            candidates = []
            for t in range(1, n + 1):
                if count[t] > max_count:
                    max_count = count[t]
                    candidates = [t]
                elif count[t] == max_count:
                    candidates.append(t)
            
            # Find the position of i in the permutation
            current_pos = pos[i]
            
            # Check if current_pos is among the candidates
            if current_pos not in candidates:
                valid = False
                break
            
            # Remove current_pos from available
            available.remove(current_pos)
        
        results.append("Yes" if valid else "No")
    
    print("\n".join(results))

if __name__ == '__main__':
    solve()